networks:
  catalog-microservice:
    driver: bridge

volumes:
  esdata:

services:
  catalog-api:
    build:
      dockerfile: ./src/CatalogMicroservice.API/Dockerfile
      context: .
      no_cache: true
    ports:
     - "52080:8080"
    depends_on:
     - catalog-sqlserver
     - fluent-bit
    networks:
     - catalog-microservice
    restart: unless-stopped
    environment:
     - SQL_CONNECTION_STRING=Data Source=catalog-sqlserver;Integrated Security=false;User ID=sa;Password=@sineThingComplicated1234;Encrypt=false;TrustServerCertificate=true;
     - SQL_DATABASE_NAME=CatalogDatabase
     - SHOULD_SHOW_SWAGGER=true
     - SHOULD_SETUP_DB=true
     - USE_INVENTORY_MICROSERVICE=false

  catalog-sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "@sineThingComplicated1234", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
     - "52433:1433"
    volumes:
     - ./data/mssql-data:/var/opt/mssql/data
    environment:
     - SA_PASSWORD=@sineThingComplicated1234
     - ACCEPT_EULA=Y
    networks:
     - catalog-microservice
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # for testing/demo
    ports:
      - "9200:9200"
    networks:
      - catalog-microservice
    volumes:
      - esdata:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.Security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - catalog-microservice

  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:2.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    depends_on:
      - elasticsearch
    networks:
      - catalog-microservice
